"""
Common Output Schema — v4 (Revision 3+ Architecture)
Every extracted entity and relation follows this schema.
This is the ONLY format that goes to the database.

v4 changes:
  - FIR: replaced status with three lifecycle dimensions
    (investigation_status, legal_disposition, record_status)
  - Added FIRLifecycleHistory for lifecycle audit trail
  - Added CaseRelationship, CaseRelationshipHistory
  - Added CaseAccess (authorization model)
  - Added InvestigationWorkspace, WorkspaceCase, WorkspaceMember
  - Added AnalysisRun, AnalysisRunCase, AnalysisRunResult
  - Added Finding (conclusions/hypotheses/critic output)
  - Case ↔ FIR 1:1 invariant enforced (FIR.case_id unique)
  - FIR number uniqueness scoped to jurisdiction
  - All models have to_dict() for serialization
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict
from datetime import datetime
from enum import Enum
import json
import hashlib


# ──────────────────────────────────────────────
# Enums — Pipeline Core
# ──────────────────────────────────────────────

class EntityType(Enum):
    """Entity types — pipeline uses 16 types for comprehensive coverage."""
    PERSON = "PERSON"
    PHONE = "PHONE"
    VEHICLE = "VEHICLE"
    LOCATION = "LOCATION"
    ACCOUNT = "ACCOUNT"
    ORGANIZATION = "ORGANIZATION"
    EVENT = "EVENT"
    DEVICE = "DEVICE"
    AMOUNT = "AMOUNT"
    DATE = "DATE"
    DOCUMENT = "DOCUMENT"
    EMAIL = "EMAIL"
    VEHICLE_PLATE = "VEHICLE_PLATE"
    IP_ADDRESS = "IP_ADDRESS"
    CASE_NUMBER = "CASE_NUMBER"
    UNKNOWN = "UNKNOWN"


class RelationType(Enum):
    """Relation types — pipeline uses 16 types for comprehensive coverage."""
    # Communication
    CALLED = "CALLED"
    MESSED = "MESSED"
    ASSOCIATED_WITH = "ASSOCIATED_WITH"
    # Financial
    TRANSFERRED_TO = "TRANSFERRED_TO"
    RECEIVED_FROM = "RECEIVED_FROM"
    OWNS_ACCOUNT = "OWNS_ACCOUNT"
    # Personal
    FAMILY_OF = "FAMILY_OF"
    FRIEND_OF = "FRIEND_OF"
    ASSOCIATE_OF = "ASSOCIATE_OF"
    WORKS_WITH = "WORKS_WITH"
    # Location
    LIVES_AT = "LIVES_AT"
    WORKS_AT = "WORKS_AT"
    VISITED = "VISITED"
    # Event
    SUSPECT_OF = "SUSPECT_OF"
    VICTIM_OF = "VICTIM_OF"
    WITNESS_OF = "WITNESS_OF"
    # Organization
    MEMBER_OF = "MEMBER_OF"
    # Provenance
    EXTRACTED_FROM = "EXTRACTED_FROM"
    DERIVED_FROM = "DERIVED_FROM"
    # Identity
    POSSIBLE_IDENTITY = "POSSIBLE_IDENTITY"
    SAME_AS = "SAME_AS"


class ProvenanceClass(Enum):
    """Provenance classification — how data was obtained."""
    OBSERVATIONAL = "OBSERVATIONAL"      # Direct sensor/person record
    DERIVED = "DERIVED"                  # Computed from other data
    INVESTIGATIVE = "INVESTIGATIVE"      # Generated by investigation
    MODEL_GENERATED = "MODEL_GENERATED"  # Produced by ML/AI


class VerificationStatus(Enum):
    """Verification status — how verified is this data."""
    UNVERIFIED = "UNVERIFIED"
    CORROBORATED = "CORROBORATED"
    INDEPENDENTLY_VERIFIED = "INDEPENDENTLY_VERIFIED"
    LEGALLY_ESTABLISHED = "LEGALLY_ESTABLISHED"


class EpistemicCategory(Enum):
    """What kind of knowledge claim this is — per docs: OBSERVATION ≠ INFERENCE ≠ HYPOTHESIS"""
    OBSERVATION = "OBSERVATION"        # Direct record (CDR entry, bank transaction)
    INFERENCE = "INFERENCE"            # Derived from observations (entity resolution)
    HYPOTHESIS = "HYPOTHESIS"         # Investigator theory (not in graph as fact)
    UNKNOWN_PROVENANCE = "UNKNOWN_PROVENANCE"  # Cannot determine


class SemanticEdgeType(Enum):
    """Relationship semantics — per DATA_FLOW.md Stage 5 step 3"""
    ENTREPRENEURIAL = "entrepreneurial"      # business/profit
    ASSOCIATIONAL = "associational"          # social/bonding
    QUASI_GOVERNMENTAL = "quasi-governmental"  # governance/enforcement


class ContradictionType(Enum):
    """Full contradiction taxonomy — per SYSTEM_STRUCTURE.md 8 types"""
    IDENTITY = "identity"           # Same person, different identity
    TEMPORAL = "temporal"           # Conflicting timestamps
    LOCATION = "location"           # Conflicting locations
    ATTRIBUTION = "attribution"     # Different source claims different owner
    SOURCE_CONTENT = "source_content"  # Same fact described differently across sources
    EVENT_IDENTITY = "event_identity"  # Same event described as different events
    DERIVATION = "derivation"       # Derived claim contradicts its source observations
    UNKNOWN = "unknown"             # Cannot classify the contradiction type


class ContradictionSeverity(Enum):
    """Contradiction severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ──────────────────────────────────────────────
# Enums — Domain Models
# ──────────────────────────────────────────────

class Gender(Enum):
    """Person gender."""
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"


class CaseStatus(Enum):
    """Case lifecycle status."""
    ACTIVE = "ACTIVE"
    PENDING = "PENDING"
    SOLVED = "SOLVED"
    CLOSED = "CLOSED"


class UserRole(Enum):
    """User roles."""
    INSPECTOR = "INSPECTOR"
    ADMIN = "ADMIN"
    AUDIT_LOGGER = "AUDIT_LOGGER"


class UserStatus(Enum):
    """User account status."""
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    FORCE_PASSWORD_CHANGE = "FORCE_PASSWORD_CHANGE"


class SuspectStatus(Enum):
    """Suspect lifecycle status."""
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"
    ARRESTED = "ARRESTED"
    CHARGED = "CHARGED"
    CONVICTED = "CONVICTED"
    ACQUITTED = "ACQUITTED"
    RELEASED = "RELEASED"


class EvidenceStatus(Enum):
    """Evidence lifecycle status."""
    LOGGED = "LOGGED"
    COLLECTED = "COLLECTED"
    ANALYZED = "ANALYZED"
    ADMITTED = "ADMITTED"
    DISMISSED = "DISMISSED"


class CaseEntityRole(Enum):
    """Role of a person in a case."""
    SUSPECT = "SUSPECT"
    VICTIM = "VICTIM"
    WITNESS = "WITNESS"
    ASSOCIATE = "ASSOCIATE"
    VEHICLE_OWNER = "VEHICLE_OWNER"


class MergeType(Enum):
    """Entity resolution merge type."""
    AUTO = "AUTO"
    REVIEW = "REVIEW"
    REJECT = "REJECT"
    SINGLE = "SINGLE"
    LLM = "LLM"


class CandidateStatus(Enum):
    """Entity resolution candidate status."""
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


class GraphNodeResolutionStatus(Enum):
    """Graph node resolution status."""
    RESOLVED = "RESOLVED"
    STANDALONE = "STANDALONE"
    UNRESOLVED = "UNRESOLVED"


class AdversarialRiskLevel(Enum):
    """Adversarial risk levels."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FaceStatus(Enum):
    """Face embedding status."""
    PENDING = "PENDING"
    EXTRACTED = "EXTRACTED"
    MATCHED = "MATCHED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    LOW_QUALITY = "LOW_QUALITY"


class SourceType(Enum):
    """Source types for ingested files."""
    CDR = "CDR"
    BANK = "BANK"
    FIR = "FIR"
    CCTV = "CCTV"
    SOCIAL = "SOCIAL"
    DEVICE = "DEVICE"
    TEXT = "TEXT"
    DOCUMENT = "DOCUMENT"
    IMAGE = "IMAGE"
    AUDIO = "AUDIO"
    VIDEO = "VIDEO"
    UNKNOWN = "UNKNOWN"


class DocumentType(Enum):
    """Document types for ingested files."""
    FIR = "FIR"
    CDR = "CDR"
    BANK_RECORD = "BANK_RECORD"
    CCTV_LOG = "CCTV_LOG"
    SOCIAL_MEDIA = "SOCIAL_MEDIA"
    DEVICE_FORENSIC = "DEVICE_FORENSIC"
    WITNESS_STATEMENT = "WITNESS_STATEMENT"
    SURVEILLANCE_REPORT = "SURVEILLANCE_REPORT"
    JOURNALIST_NOTE = "JOURNALIST_NOTE"
    INVESTIGATOR_SUMMARY = "INVESTIGATOR_SUMMARY"
    UNKNOWN = "UNKNOWN"


class PipelineRunStatus(Enum):
    """Pipeline run status."""
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


# ──────────────────────────────────────────────
# Enums — Jurisdiction & Multi-Case
# ──────────────────────────────────────────────

class JurisdictionNodeType(Enum):
    """Types of nodes in the police organizational hierarchy.
    Extensible — different states use different structures."""
    NATION = "nation"
    STATE_UT = "state_ut"
    COMMISSIONERATE = "commissionerate"
    RANGE = "range"
    DISTRICT = "district"
    CITY = "city"
    ZONE = "zone"
    DIVISION = "division"
    SUB_DIVISION = "sub_division"
    POLICE_STATION = "police_station"
    OUT_POST = "out_post"


class JurisdictionNodeStatus(Enum):
    """Status of a jurisdiction node."""
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    MERGED = "MERGED"
    SPLIT = "SPLIT"


class CaseJurisdictionLinkType(Enum):
    """Types of jurisdiction links on a case."""
    PRIMARY = "primary"
    ASSIST = "assist"
    TRANSFER = "transfer"
    LINKED = "linked"


class UnresolvedJurisdictionStatus(Enum):
    """Status of an unresolved jurisdiction record."""
    UNRESOLVED = "UNRESOLVED"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"


class CrossCaseAlertSeverity(Enum):
    """Severity levels for cross-case alerts."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ──────────────────────────────────────────────
# Enums — CaseRelationship
# ──────────────────────────────────────────────

class CaseRelationshipAssessment(Enum):
    """Current assessment of how two independent Cases relate."""
    SHARED_ENTITY = "SHARED_ENTITY"
    POSSIBLE_SAME_INCIDENT = "POSSIBLE_SAME_INCIDENT"
    POSSIBLE_RELATED_CASE = "POSSIBLE_RELATED_CASE"
    SAME_INCIDENT = "SAME_INCIDENT"
    RELATED_CASE = "RELATED_CASE"


class CaseRelationshipStatus(Enum):
    """Status of a CaseRelationship."""
    SUGGESTED = "SUGGESTED"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"


# ──────────────────────────────────────────────
# Enums — CaseAccess
# ──────────────────────────────────────────────

class CaseAccessLevel(Enum):
    """Authorization level for Case access."""
    READ = "READ"
    WRITE = "WRITE"
    ADMIN = "ADMIN"


# ──────────────────────────────────────────────
# Enums — InvestigationWorkspace
# ──────────────────────────────────────────────

class WorkspaceRole(Enum):
    """Role within an InvestigationWorkspace."""
    OWNER = "OWNER"
    MEMBER = "MEMBER"
    VIEWER = "VIEWER"


class WorkspaceStatus(Enum):
    """Workspace status."""
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


# ──────────────────────────────────────────────
# Enums — AnalysisRun
# ──────────────────────────────────────────────

class AnalysisRunScopeType(Enum):
    """Scope of an AnalysisRun."""
    LOCAL = "LOCAL"
    SCOPED = "SCOPED"


class AnalysisRunStatus(Enum):
    """AnalysisRun execution status."""
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# ──────────────────────────────────────────────
# Enums — Finding
# ──────────────────────────────────────────────

class FindingType(Enum):
    """Type of finding."""
    HYPOTHESIS = "HYPOTHESIS"
    ANOMALY = "ANOMALY"
    PATTERN = "PATTERN"
    CRITIC_VERDICT = "CRITIC_VERDICT"


class CriticStatus(Enum):
    """Critic evaluation status."""
    PENDING = "PENDING"
    CORROBORATED = "CORROBORATED"
    REFUTED = "REFUTED"
    INCONCLUSIVE = "INCONCLUSIVE"


# ──────────────────────────────────────────────
# Enums — FIR Lifecycle
# ──────────────────────────────────────────────

class FIRInvestigationStatus(Enum):
    """Police operational lifecycle of a FIR."""
    REGISTERED = "REGISTERED"
    UNDER_INVESTIGATION = "UNDER_INVESTIGATION"
    CHARGE_SHEETED = "CHARGE_SHEETED"
    FINAL_REPORT = "FINAL_REPORT"
    CLOSED = "CLOSED"


class FIRLegalDisposition(Enum):
    """Court/legal disposition of a FIR."""
    NONE = "NONE"
    CANCELLED = "CANCELLED"
    QUASHED = "QUASHED"
    DISPOSED = "DISPOSED"
    CONVICTED = "CONVICTED"
    ACQUITTED = "ACQUITTED"


class FIRRecordStatus(Enum):
    """Administrative/archive state of a FIR."""
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"
    SEALED = "SEALED"


class FIRLifecycleDimension(Enum):
    """Which FIR lifecycle dimension is being transitioned."""
    INVESTIGATION_STATUS = "INVESTIGATION_STATUS"
    LEGAL_DISPOSITION = "LEGAL_DISPOSITION"
    RECORD_STATUS = "RECORD_STATUS"


# ──────────────────────────────────────────────
# Pipeline Run Versioning
# ──────────────────────────────────────────────

@dataclass
class PipelineRun:
    """Every pipeline execution is a discrete run — per DATA_FLOW.md"""
    run_id: str                     # "run_001"
    case_id: str                    # "CASE_001"
    input_snapshot: List[str]       # RawEvidence IDs included in this run
    jurisdiction_node_id: Optional[str] = None  # FK → JurisdictionNode (denormalized)
    pipeline_version: str = "v1.0"
    model_versions: dict = field(default_factory=dict)  # {ner: "v2.1", ...}
    policy_version: str = "policy_v1.0"
    start_time: str = ""
    end_time: str = ""
    parent_run_id: Optional[str] = None
    trigger: str = "new_evidence"   # new_evidence/reprocessing/policy_change/manual
    status: str = "running"         # running/completed/failed

    def to_dict(self):
        return {
            "run_id": self.run_id,
            "case_id": self.case_id,
            "input_snapshot": self.input_snapshot,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "pipeline_version": self.pipeline_version,
            "model_versions": self.model_versions,
            "policy_version": self.policy_version,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "parent_run_id": self.parent_run_id,
            "trigger": self.trigger,
            "status": self.status,
        }


# ──────────────────────────────────────────────
# Source Reliability Matrix
# ──────────────────────────────────────────────

# Per docs: reliability depends on WHAT CLAIM is being made
# source_type × claim_type → reliability score
SOURCE_RELIABILITY_MATRIX: Dict[str, Dict[str, float]] = {
    "cdr": {
        "occurrence": 0.95,    # CDR reliably records that a call happened
        "identity": 0.60,      # Phone owner ≠ caller (SIM sharing)
        "location": 0.80,      # Tower-based, not GPS
        "timing": 0.95,        # Network timestamps are reliable
        "duration": 0.95,      # Network-recorded
        "intent": 0.30,        # Cannot infer intent from CDR
    },
    "bank": {
        "occurrence": 0.98,    # Bank records are authoritative
        "identity": 0.85,      # Account holder name is usually correct
        "location": 0.40,      # Branch location ≠ transaction location
        "timing": 0.95,        # Bank timestamps are reliable
        "duration": 0.0,       # N/A
        "intent": 0.50,        # Description field gives partial intent
    },
    "fir": {
        "occurrence": 0.80,    # FIR describes alleged events
        "identity": 0.70,      # Names may be misspelled
        "location": 0.75,      # Addresses in FIR are usually correct
        "timing": 0.70,        # Dates may be approximate
        "duration": 0.40,      # Rarely precise
        "intent": 0.60,        # Describes alleged intent
    },
    "cctv": {
        "occurrence": 0.90,    # CCTV captures what happened
        "identity": 0.50,      # Face recognition uncertain
        "location": 0.95,      # Camera location is fixed
        "timing": 0.90,        # Timestamp usually reliable
        "duration": 0.85,      # Can measure duration
        "intent": 0.20,        # Cannot infer intent
    },
    "social": {
        "occurrence": 0.85,    # Posts are real
        "identity": 0.60,      # Profile name ≠ real name
        "location": 0.70,      # Tagged location may be inaccurate
        "timing": 0.80,        # Post date is usually correct
        "duration": 0.0,       # N/A
        "intent": 0.50,        # Caption gives partial intent
    },
    "device": {
        "occurrence": 0.95,    # Device extraction is direct
        "identity": 0.90,      # Device owner is usually known
        "location": 0.85,      # GPS/exif data
        "timing": 0.90,        # Device timestamps
        "duration": 0.80,      # App usage duration
        "intent": 0.40,        # App usage ≠ intent
    },
    "text": {
        "occurrence": 0.70,    # Text reports describe events
        "identity": 0.65,      # Names may be approximate
        "location": 0.70,      # Addresses in text
        "timing": 0.65,        # Dates may be approximate
        "duration": 0.40,      # Rarely precise
        "intent": 0.50,        # Reporter's interpretation
    },
}


def get_reliability(source_type: str, claim_type: str) -> float:
    """Get reliability score from matrix. Returns 0.5 if unknown."""
    return SOURCE_RELIABILITY_MATRIX.get(source_type, {}).get(claim_type, 0.5)


# ──────────────────────────────────────────────
# Evidence Integrity
# ──────────────────────────────────────────────

@dataclass
class EvidenceIntegrity:
    """Chain of custody for evidence — per docs"""
    file_hash: str                  # SHA-256 of original file
    original_filename: str
    ingestion_time: str
    case_id: str = ""               # FK → Case
    jurisdiction_node_id: str = ""  # FK → JurisdictionNode
    chain_of_custody: List[dict] = field(default_factory=list)
    # Each entry: {action: "ingested"|"transformed"|"accessed", timestamp, by, hash_before, hash_after}
    transformations: List[dict] = field(default_factory=list)
    # Each entry: {type: "ocr"|"encoding"|"trimming", input_hash, output_hash, timestamp}

    def add_custody_event(self, action: str, by: str = "system", hash_before: str = "", hash_after: str = ""):
        self.chain_of_custody.append({
            "action": action,
            "timestamp": datetime.now().isoformat(),
            "by": by,
            "hash_before": hash_before,
            "hash_after": hash_after,
        })

    def add_transformation(self, transform_type: str, input_hash: str, output_hash: str):
        self.transformations.append({
            "type": transform_type,
            "input_hash": input_hash,
            "output_hash": output_hash,
            "timestamp": datetime.now().isoformat(),
        })

    def to_dict(self):
        return {
            "file_hash": self.file_hash,
            "original_filename": self.original_filename,
            "ingestion_time": self.ingestion_time,
            "chain_of_custody": self.chain_of_custody,
            "transformations": self.transformations,
        }


# ──────────────────────────────────────────────
# Dependency Tracking
# ──────────────────────────────────────────────

@dataclass
class DependencyGroup:
    """Tracks which sources share sub-sources — per docs"""
    group_id: str
    sources: List[str]              # file names in this group
    dependency_type: str            # "same_file" | "same_fir" | "independent"
    description: str = ""

    def to_dict(self):
        return {
            "group_id": self.group_id,
            "sources": self.sources,
            "dependency_type": self.dependency_type,
            "description": self.description,
        }


# ──────────────────────────────────────────────
# Provenance Chain
# ──────────────────────────────────────────────

@dataclass
class ProvenanceChain:
    """Trace back to raw evidence — per DATA_FLOW.md Stage 5 step 4"""
    id: str
    node_id: str                    # Entity or edge this traces to
    derivation_type: str            # "extracted" | "inferred" | "derived"
    depth: int                      # 0=raw, 1=inferred, 2=derived
    source_evidence: List[str]      # RawEvidence IDs
    derivation: List[dict] = field(default_factory=list)  # [{step, type, id}] step-by-step chain
    is_independent: bool = True
    dependency_group: str = ""      # DependencyGroup ID
    run_id: str = ""                # Pipeline run ID

    def to_dict(self):
        return {
            "id": self.id,
            "node_id": self.node_id,
            "derivation_type": self.derivation_type,
            "depth": self.depth,
            "source_evidence": self.source_evidence,
            "derivation": self.derivation,
            "is_independent": self.is_independent,
            "dependency_group": self.dependency_group,
            "run_id": self.run_id,
        }


# ──────────────────────────────────────────────
# Confidence with Structured Factors
# ──────────────────────────────────────────────

@dataclass
class ConfidenceFactor:
    """One factor contributing to confidence — structured decomposition"""
    factor_type: str                # "source_reliability" | "corroboration" | "temporal" | etc.
    value: float                    # 0.0 - 1.0
    weight: float = 1.0             # How much this factor matters
    description: str = ""

    def to_dict(self):
        return {
            "factor_type": self.factor_type,
            "value": self.value,
            "weight": self.weight,
            "description": self.description,
        }


@dataclass
class ConfidenceSchema:
    """Unified confidence with decomposition — per docs"""
    score: float  # 0.0 - 1.0
    basis: List[str] = field(default_factory=list)
    supporting_count: int = 0
    contradicting_count: int = 0
    unknown_count: int = 0
    source_reliability: float = 0.0
    derivation_depth: int = 0  # 0=raw, 1=inferred, 2=derived
    is_independent: bool = True
    last_verified: Optional[str] = None
    staleness: str = "current"  # current/recent/old/very_old
    semantic_type: str = ""     # "observation" | "inference" | "hypothesis"
    run_id: str = ""            # Which pipeline run produced this
    model_version: str = ""     # Which model version produced this
    factors: List[ConfidenceFactor] = field(default_factory=list)  # Structured decomposition

    def __post_init__(self):
        """Auto-populate factors if empty."""
        if not self.factors:
            self.factors = [
                ConfidenceFactor(
                    factor_type="source_reliability",
                    value=self.source_reliability if self.source_reliability > 0 else 0.5,
                    weight=0.4,
                    description=f"Source reliability: {self.source_reliability:.2f}",
                ),
                ConfidenceFactor(
                    factor_type="evidence_basis",
                    value=min(1.0, self.score),
                    weight=0.6,
                    description=self.basis[0] if self.basis else "No basis specified",
                ),
            ]

    @classmethod
    def create(cls, score: float, basis: List[str], source_type: str = "text",
               epistemic: str = "observation", derivation_depth: int = 0,
               run_id: str = "") -> "ConfidenceSchema":
        """Create ConfidenceSchema with proper factors from source type."""
        reliability = get_reliability(source_type, "occurrence") if source_type else 0.5
        factors = [
            ConfidenceFactor(
                factor_type="source_reliability",
                value=reliability,
                weight=0.4,
                description=f"Reliability for {source_type} source",
            ),
            ConfidenceFactor(
                factor_type="evidence_basis",
                value=min(1.0, score),
                weight=0.6,
                description=basis[0] if basis else "",
            ),
        ]
        return cls(
            score=score,
            basis=basis,
            source_reliability=reliability,
            derivation_depth=derivation_depth,
            semantic_type=epistemic,
            run_id=run_id,
            factors=factors,
        )

    def to_dict(self):
        return {
            "score": self.score,
            "basis": self.basis,
            "supporting_count": self.supporting_count,
            "contradicting_count": self.contradicting_count,
            "unknown_count": self.unknown_count,
            "source_reliability": self.source_reliability,
            "derivation_depth": self.derivation_depth,
            "is_independent": self.is_independent,
            "last_verified": self.last_verified,
            "staleness": self.staleness,
            "semantic_type": self.semantic_type,
            "run_id": self.run_id,
            "model_version": self.model_version,
            "factors": [f.to_dict() for f in self.factors],
        }


@dataclass
class SourceMetadata:
    """Where this data came from"""
    source_type: str           # "cdr", "fir", "bank", "cctv", "social", "device"
    file_name: str             # original filename
    file_hash: str             # SHA-256
    ingestion_time: str        # ISO timestamp
    case_id: str = ""          # FK → Case
    jurisdiction_node_id: str = ""  # FK → JurisdictionNode
    provenance: ProvenanceClass = ProvenanceClass.OBSERVATIONAL
    verification: VerificationStatus = VerificationStatus.UNVERIFIED
    reliability_occurrence: float = 0.0
    reliability_identity: float = 0.0
    reliability_intent: float = 0.0
    reliability_location: float = 0.0
    reliability_timing: float = 0.0
    adversarial_suspicious: bool = False  # Stage 1 adversarial flag propagated to Stage 5

    def to_dict(self):
        return {
            "source_type": self.source_type,
            "file_name": self.file_name,
            "file_hash": self.file_hash,
            "ingestion_time": self.ingestion_time,
            "provenance": self.provenance.value,
            "verification": self.verification.value,
            "reliability_occurrence": self.reliability_occurrence,
            "reliability_identity": self.reliability_identity,
            "reliability_intent": self.reliability_intent,
            "reliability_location": self.reliability_location,
            "reliability_timing": self.reliability_timing,
            "adversarial_suspicious": self.adversarial_suspicious,
        }


# ──────────────────────────────────────────────
# Stage 2: Extraction Types
# ──────────────────────────────────────────────

@dataclass
class ExtractedEntity:
    """One entity extracted from data — per DATA_FLOW.md Stage 2"""
    id: str
    entity_type: EntityType
    name: str
    case_id: str = ""                 # FK → Case (which case this was extracted from)
    aliases: List[str] = field(default_factory=list)
    attributes: dict = field(default_factory=dict)
    confidence: ConfidenceSchema = None
    source: SourceMetadata = None
    raw_text: Optional[str] = None
    extraction_method: str = "code"  # "code", "llm", "vision"
    source_id: str = ""              # Which RawEvidence this came from
    epistemic_category: str = "observation"  # observation/inference/hypothesis
    derivation_depth: int = 0        # 0=raw, 1=inferred, 2=derived
    run_id: str = ""                 # Which pipeline run produced this

    def to_dict(self):
        return {
            "id": self.id,
            "entity_type": self.entity_type.value,
            "name": self.name,
            "case_id": self.case_id,
            "aliases": self.aliases,
            "attributes": self.attributes,
            "confidence": self.confidence.to_dict() if self.confidence else None,
            "source": self.source.to_dict() if self.source else None,
            "raw_text": self.raw_text,
            "extraction_method": self.extraction_method,
            "source_id": self.source_id,
            "epistemic_category": self.epistemic_category,
            "derivation_depth": self.derivation_depth,
            "run_id": self.run_id,
        }


@dataclass
class ExtractedRelation:
    """One relation extracted from data — per DATA_FLOW.md Stage 2"""
    id: str
    source_entity_id: str
    target_entity_id: str
    relation_type: RelationType
    case_id: str = ""                 # FK → Case
    confidence: ConfidenceSchema = None
    source: SourceMetadata = None
    attributes: dict = field(default_factory=dict)
    raw_text: Optional[str] = None
    extraction_method: str = "code"
    source_id: str = ""              # Which RawEvidence this came from
    epistemic_category: str = "observation"  # observation/inference/hypothesis
    derivation_depth: int = 0        # 0=raw, 1=inferred, 2=derived
    semantic_edge_type: str = ""     # entrepreneurial/associational/quasi-governmental
    temporal_info: Optional[dict] = None
    run_id: str = ""                 # Which pipeline run produced this

    def to_dict(self):
        return {
            "id": self.id,
            "source_entity_id": self.source_entity_id,
            "target_entity_id": self.target_entity_id,
            "relation_type": self.relation_type.value,
            "case_id": self.case_id,
            "confidence": self.confidence.to_dict() if self.confidence else None,
            "source": self.source.to_dict() if self.source else None,
            "attributes": self.attributes,
            "raw_text": self.raw_text,
            "extraction_method": self.extraction_method,
            "source_id": self.source_id,
            "epistemic_category": self.epistemic_category,
            "derivation_depth": self.derivation_depth,
            "semantic_edge_type": self.semantic_edge_type,
            "temporal_info": self.temporal_info,
            "run_id": self.run_id,
        }


def generate_id(prefix: str, content: str) -> str:
    """Generate a deterministic ID from content using SHA-256 (16 hex chars = 64 bits)"""
    hash_val = hashlib.sha256(content.encode()).hexdigest()[:16]
    return f"{prefix}_{hash_val}"


def file_hash(file_path: str) -> str:
    """Calculate SHA-256 hash of a file — full 64 hex chars for evidence integrity"""
    sha256 = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            sha256.update(chunk)
    return f"sha256:{sha256.hexdigest()}"


# ──────────────────────────────────────────────
# Stage 3: Entity Resolution Types
# ──────────────────────────────────────────────

@dataclass
class ResolvedEntity:
    """A canonical entity created by merging multiple extracted entities — per DATA_FLOW.md Stage 3"""
    id: str
    canonical_name: str
    entity_type: str
    case_id: str = ""                 # FK → Case (local to this case)
    aliases: List[str] = field(default_factory=list)
    phones: List[str] = field(default_factory=list)
    accounts: List[str] = field(default_factory=list)
    addresses: List[str] = field(default_factory=list)
    attributes: dict = field(default_factory=dict)
    merge_confidence: float = 0.0
    merge_type: str = "auto"  # auto, review, reject
    source_entities: List[str] = field(default_factory=list)
    source_relations: List[str] = field(default_factory=list)
    llm_reasoning: str = ""
    signals: dict = field(default_factory=dict)
    contradictions: List[str] = field(default_factory=list)
    created_at: str = ""
    updated_at: str = ""
    epistemic_status: str = "observation"  # observation/inference/hypothesis
    derivation_depth: int = 0
    provenance_chain: List[str] = field(default_factory=list)  # Evidence IDs
    effective_confidence: float = 0.0  # f(hypothesis_confidence, identity_confidence)
    run_id: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "canonical_name": self.canonical_name,
            "entity_type": self.entity_type,
            "case_id": self.case_id,
            "aliases": self.aliases,
            "phones": self.phones,
            "accounts": self.accounts,
            "addresses": self.addresses,
            "attributes": self.attributes,
            "merge_confidence": self.merge_confidence,
            "merge_type": self.merge_type,
            "source_entities": self.source_entities,
            "source_relations": self.source_relations,
            "llm_reasoning": self.llm_reasoning,
            "signals": self.signals,
            "contradictions": self.contradictions,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "epistemic_status": self.epistemic_status,
            "derivation_depth": self.derivation_depth,
            "provenance_chain": self.provenance_chain,
            "effective_confidence": self.effective_confidence,
            "run_id": self.run_id,
        }


@dataclass
class UnknownEntity:
    """An entity that could not be resolved to a known person/organization."""
    id: str
    description: str
    entity_type: str
    source_entity: str = ""
    attributes: dict = field(default_factory=dict)
    possible_matches: List[str] = field(default_factory=list)
    confidence: float = 0.0

    def to_dict(self):
        return {
            "id": self.id,
            "description": self.description,
            "entity_type": self.entity_type,
            "source_entity": self.source_entity,
            "attributes": self.attributes,
            "possible_matches": self.possible_matches,
            "confidence": self.confidence,
        }


@dataclass
class Contradiction:
    """A conflict detected between entities — per docs"""
    id: str
    type: str  # identity/temporal/location/attribution/attribute/role
    entity_ids: List[str] = field(default_factory=list)
    attribute: str = ""
    values: List[str] = field(default_factory=list)
    sources: List[str] = field(default_factory=list)
    severity: str = "medium"  # low, medium, high, critical
    resolved: bool = False
    resolution_note: str = ""
    derivation_depth: int = 0
    epistemic_category: str = "observation"
    run_id: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "type": self.type,
            "entity_ids": self.entity_ids,
            "attribute": self.attribute,
            "values": self.values,
            "sources": self.sources,
            "severity": self.severity,
            "resolved": self.resolved,
            "resolution_note": self.resolution_note,
            "run_id": self.run_id,
        }


@dataclass
class DataQualityScore:
    """Per-file data quality assessment — per docs"""
    file_name: str
    quality_score: float = 0.0        # 0.0 - 1.0
    completeness_score: float = 0.0   # 0.0 - 1.0
    structural_consistency: float = 0.0  # Column uniformity, encoding issues
    content_richness: float = 0.0     # Non-empty fields ratio
    issues: List[str] = field(default_factory=list)
    run_id: str = ""

    def to_dict(self):
        return {
            "file_name": self.file_name,
            "quality_score": self.quality_score,
            "completeness_score": self.completeness_score,
            "structural_consistency": self.structural_consistency,
            "content_richness": self.content_richness,
            "issues": self.issues,
            "run_id": self.run_id,
        }


@dataclass
class AdversarialCheck:
    """Adversarial data integrity check — per docs"""
    file_name: str
    is_suspicious: bool = False
    behavioral_anomaly: bool = False    # Unusual patterns for source type
    temporal_anomaly: bool = False      # Timestamps outside expected range
    content_anomaly: bool = False       # Unusual content for claimed source type
    duplicate_suspect: bool = False     # Near-duplicate content from different sources
    score: float = 0.0                  # 0.0 = clean, 1.0 = highly suspicious
    reasons: List[str] = field(default_factory=list)
    run_id: str = ""

    def to_dict(self):
        return {
            "file_name": self.file_name,
            "is_suspicious": self.is_suspicious,
            "behavioral_anomaly": self.behavioral_anomaly,
            "temporal_anomaly": self.temporal_anomaly,
            "content_anomaly": self.content_anomaly,
            "duplicate_suspect": self.duplicate_suspect,
            "score": self.score,
            "reasons": self.reasons,
            "run_id": self.run_id,
        }


@dataclass
class ResolutionHistory:
    """Tracks every resolution decision for audit — per docs"""
    entity_id: str
    resolution_type: str          # "merge", "split", "reject", "unknown"
    merged_with: List[str] = field(default_factory=list)
    confidence: float = 0.0
    method: str = ""              # "rule", "phonetic", "fuzzy", "multi_signal", "llm"
    signals: dict = field(default_factory=dict)
    timestamp: str = ""
    run_id: str = ""
    previous_state: str = ""      # What the entity was before this resolution

    def to_dict(self):
        return {
            "entity_id": self.entity_id,
            "resolution_type": self.resolution_type,
            "merged_with": self.merged_with,
            "confidence": self.confidence,
            "method": self.method,
            "signals": self.signals,
            "timestamp": self.timestamp,
            "run_id": self.run_id,
            "previous_state": self.previous_state,
        }


@dataclass
class MergeCandidate:
    """A group of entities that might be the same real-world entity."""
    entity_ids: List[str]
    signal: str  # first_name, partial_name, shared_phone, exact_name
    description: str = ""
    confidence: float = 0.0
    entities: List[dict] = field(default_factory=list)


@dataclass
class LLMVerdict:
    """LLM evaluation result for a candidate group."""
    entity_ids: List[str]
    merge: bool
    confidence: float
    canonical_name: str
    reasoning: str
    signals: dict = field(default_factory=dict)
    merge_type: str = "reject"
    contradictions: List[str] = field(default_factory=list)


# ──────────────────────────────────────────────
# Domain Models — FIR, Person, Suspect, Case, Evidence
# ──────────────────────────────────────────────

@dataclass
class FIR:
    """First Information Report — first-class entity in the system.
    FIR number uniqueness is jurisdiction-scoped (not global).
    FIR identity is immutable. Lifecycle fields are mutable and controlled."""
    id: str
    case_id: str                        # FK → Case (unique — one FIR per Case)
    fir_number: str
    jurisdiction_node_id: str           # FK → JurisdictionNode (which station registered this)
    description: str
    filed_by_id: str
    fir_document_r2_key: Optional[str] = None
    filed_at: str = ""                  # When the FIR was filed
    # Lifecycle fields (mutable, authorization-controlled)
    investigation_status: str = "REGISTERED"  # FIRInvestigationStatus enum value
    legal_disposition: str = "NONE"           # FIRLegalDisposition enum value
    record_status: str = "ACTIVE"             # FIRRecordStatus enum value
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "case_id": self.case_id,
            "fir_number": self.fir_number,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "description": self.description,
            "filed_by_id": self.filed_by_id,
            "fir_document_r2_key": self.fir_document_r2_key,
            "filed_at": self.filed_at,
            "investigation_status": self.investigation_status,
            "legal_disposition": self.legal_disposition,
            "record_status": self.record_status,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class Person:
    """Canonical person identity — created during entity resolution."""
    id: str
    canonical_name: str
    gender: Optional[str] = None     # Gender enum value
    dob: Optional[str] = None        # ISO date string
    national_id_number: Optional[str] = None
    photo_r2_key: Optional[str] = None
    identity_source: str = "MANUAL"  # MANUAL | FIR_INFERRED | FACE_MATCH_CONFIRMED
    name_confidence: Optional[float] = None
    created_by_id: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "canonical_name": self.canonical_name,
            "gender": self.gender,
            "dob": self.dob,
            "national_id_number": self.national_id_number,
            "photo_r2_key": self.photo_r2_key,
            "identity_source": self.identity_source,
            "name_confidence": self.name_confidence,
            "created_by_id": self.created_by_id,
            "created_at": self.created_at,
        }


@dataclass
class PersonAlias:
    """Alternative name for a person."""
    id: str
    person_id: str
    alias: str
    source: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "person_id": self.person_id,
            "alias": self.alias,
            "source": self.source,
        }


@dataclass
class Phone:
    """Phone number — linked to a person."""
    id: str
    number: str
    person_id: Optional[str] = None
    carrier: Optional[str] = None
    verified_at: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "number": self.number,
            "person_id": self.person_id,
            "carrier": self.carrier,
            "verified_at": self.verified_at,
        }


@dataclass
class Vehicle:
    """Vehicle — linked to a person."""
    id: str
    plate_number: str
    person_id: Optional[str] = None
    type: Optional[str] = None
    color: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "plate_number": self.plate_number,
            "person_id": self.person_id,
            "type": self.type,
            "color": self.color,
        }


@dataclass
class BankAccount:
    """Bank account — linked to a person."""
    id: str
    account_number_encrypted: str
    bank_name: str
    ifsc: Optional[str] = None
    person_id: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "account_number_encrypted": self.account_number_encrypted,
            "bank_name": self.bank_name,
            "ifsc": self.ifsc,
            "person_id": self.person_id,
        }


@dataclass
class Location:
    """Physical location."""
    id: str
    lat: float
    lng: float
    name: Optional[str] = None
    address: Optional[str] = None
    jurisdiction_node_id: Optional[str] = None
    geographic_jurisdiction_id: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "lat": self.lat,
            "lng": self.lng,
            "name": self.name,
            "address": self.address,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "geographic_jurisdiction_id": self.geographic_jurisdiction_id,
        }


@dataclass
class User:
    """System user — investigator, admin, audit logger."""
    id: str
    email: str
    name: str
    password_hash: str
    role: str                       # UserRole enum value
    status: str = "FORCE_PASSWORD_CHANGE"  # UserStatus enum value
    jurisdiction_node_id: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "email": self.email,
            "name": self.name,
            "role": self.role,
            "status": self.status,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class Case:
    """Case — wraps FIR and investigation.
    One Case has exactly one primary FIR (invariant).
    jurisdiction_node_id links to the primary investigating station."""
    id: str
    jurisdiction_node_id: str           # FK → JurisdictionNode (primary jurisdiction)
    location_id: Optional[str] = None
    case_status: str = "ACTIVE"         # CaseStatus enum value
    description: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "location_id": self.location_id,
            "case_status": self.case_status,
            "description": self.description,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class CaseEntityLink:
    """Links a person to a case with a role."""
    id: str
    case_id: str
    person_id: str
    role: str                       # CaseEntityRole enum value
    added_by_id: str
    added_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "case_id": self.case_id,
            "person_id": self.person_id,
            "role": self.role,
            "added_by_id": self.added_by_id,
            "added_at": self.added_at,
        }


@dataclass
class Suspect:
    """Suspect — case-scoped, resolves to Person."""
    id: str
    case_id: str
    name: str
    person_id: Optional[str] = None
    gender: Optional[str] = None     # Gender enum value
    dob: Optional[str] = None
    national_id_number: Optional[str] = None
    status: str = "UNDER_INVESTIGATION"  # SuspectStatus enum value
    arrest_date: Optional[str] = None
    contact_info: Optional[str] = None
    photo_r2_key: Optional[str] = None
    criminal_record_number: Optional[str] = None
    convicted_by_id: Optional[str] = None
    convicted_at: Optional[str] = None
    notes: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "case_id": self.case_id,
            "name": self.name,
            "person_id": self.person_id,
            "gender": self.gender,
            "dob": self.dob,
            "national_id_number": self.national_id_number,
            "status": self.status,
            "arrest_date": self.arrest_date,
            "contact_info": self.contact_info,
            "photo_r2_key": self.photo_r2_key,
            "criminal_record_number": self.criminal_record_number,
            "convicted_by_id": self.convicted_by_id,
            "convicted_at": self.convicted_at,
            "notes": self.notes,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class Evidence:
    """Evidence — tied to a case, optionally to a suspect."""
    id: str
    case_id: str
    type: str                       # PHYSICAL | DIGITAL | DOCUMENTARY | BIOLOGICAL | TESTIMONIAL
    logged_by_id: str
    suspect_id: Optional[str] = None
    status: str = "LOGGED"          # EvidenceStatus enum value
    description: Optional[str] = None
    collected_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "case_id": self.case_id,
            "type": self.type,
            "logged_by_id": self.logged_by_id,
            "suspect_id": self.suspect_id,
            "status": self.status,
            "description": self.description,
            "collected_at": self.collected_at,
        }


@dataclass
class EvidenceFile:
    """File attached to evidence — stored in R2."""
    id: str
    evidence_id: str
    file_type: str                  # AUDIO | IMAGE | DOCUMENT | VIDEO | CSV
    r2_key: str
    uploaded_by_id: str
    mime_type: Optional[str] = None
    original_file_name: Optional[str] = None
    size_bytes: Optional[int] = None
    uploaded_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "evidence_id": self.evidence_id,
            "file_type": self.file_type,
            "r2_key": self.r2_key,
            "uploaded_by_id": self.uploaded_by_id,
            "mime_type": self.mime_type,
            "original_file_name": self.original_file_name,
            "size_bytes": self.size_bytes,
            "uploaded_at": self.uploaded_at,
        }


@dataclass
class FaceEmbedding:
    """Face embedding — for face recognition module."""
    id: str
    source_image_r2_key: str
    embedding_vector: List[float]   # 512-d vector
    detector_confidence: float
    person_id: Optional[str] = None
    suspect_id: Optional[str] = None
    evidence_file_id: Optional[str] = None
    source_type: Optional[str] = None  # FIR_ANNEXURE | CCTV_STILL | SOCIAL_MEDIA | SUSPECT_BOOKING_PHOTO
    match_confidence: Optional[float] = None
    status: str = "PENDING"         # FaceStatus enum value
    confirmed_by_id: Optional[str] = None
    confirmed_at: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "source_image_r2_key": self.source_image_r2_key,
            "detector_confidence": self.detector_confidence,
            "person_id": self.person_id,
            "suspect_id": self.suspect_id,
            "evidence_file_id": self.evidence_file_id,
            "source_type": self.source_type,
            "match_confidence": self.match_confidence,
            "status": self.status,
            "confirmed_by_id": self.confirmed_by_id,
            "confirmed_at": self.confirmed_at,
            "created_at": self.created_at,
        }


@dataclass
class AuditLog:
    """Audit log — tracks all system actions."""
    id: str
    user_id: str
    action: str
    resource_type: str
    resource_id: str
    metadata: Optional[dict] = None
    ip_address: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "action": self.action,
            "resource_type": self.resource_type,
            "resource_id": self.resource_id,
            "metadata": self.metadata,
            "ip_address": self.ip_address,
            "created_at": self.created_at,
        }


# ──────────────────────────────────────────────
# Jurisdiction Hierarchy Models
# ──────────────────────────────────────────────

@dataclass
class JurisdictionNode:
    """Configurable police organizational hierarchy node.
    Forms a tree via parent_id. Level is derived, not stored."""
    id: str
    name: str
    node_type: str                      # JurisdictionNodeType enum value
    parent_id: Optional[str] = None
    status: str = "ACTIVE"              # JurisdictionNodeStatus enum value
    code: Optional[str] = None          # Official code: "DL-SE-001"
    valid_from: str = ""                # When this node became active
    valid_to: Optional[str] = None      # When deactivated (reorganization)
    created_at: str = ""
    updated_at: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "node_type": self.node_type,
            "parent_id": self.parent_id,
            "status": self.status,
            "code": self.code,
            "valid_from": self.valid_from,
            "valid_to": self.valid_to,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class GeographicJurisdiction:
    """Geographic area served by police. Separate from organizational hierarchy."""
    id: str
    name: str
    jurisdiction_type: str              # "state", "district", "city", "zone", "area"
    parent_id: Optional[str] = None
    boundary_polygon: Optional[str] = None  # GeoJSON polygon
    center_lat: Optional[float] = None
    center_lng: Optional[float] = None
    valid_from: str = ""
    valid_to: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "jurisdiction_type": self.jurisdiction_type,
            "parent_id": self.parent_id,
            "boundary_polygon": self.boundary_polygon,
            "center_lat": self.center_lat,
            "center_lng": self.center_lng,
            "valid_from": self.valid_from,
            "valid_to": self.valid_to,
            "created_at": self.created_at,
        }


@dataclass
class UnresolvedJurisdiction:
    """Parser output that couldn't be matched to a JurisdictionNode.
    Surfaced for human resolution. Never auto-creates authoritative nodes."""
    id: str
    raw_text: str                       # What the parser extracted
    source_file: str                    # Which evidence file
    source_type: str                    # "fir_text", "cdr_header", "ocr_output"
    confidence: float = 0.0             # Parser confidence (0.0-1.0)
    suggested_jurisdiction_node_id: Optional[str] = None  # FK if fuzzy match found
    resolved_by_id: Optional[str] = None  # FK → User (who resolved it)
    resolved_jurisdiction_node_id: Optional[str] = None  # FK after resolution
    status: str = "UNRESOLVED"          # UnresolvedJurisdictionStatus enum value
    created_at: str = ""
    resolved_at: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "raw_text": self.raw_text,
            "source_file": self.source_file,
            "source_type": self.source_type,
            "confidence": self.confidence,
            "suggested_jurisdiction_node_id": self.suggested_jurisdiction_node_id,
            "resolved_by_id": self.resolved_by_id,
            "resolved_jurisdiction_node_id": self.resolved_jurisdiction_node_id,
            "status": self.status,
            "created_at": self.created_at,
            "resolved_at": self.resolved_at,
        }


@dataclass
class JurisdictionHistory:
    """Audit trail for jurisdiction changes (renamed, merged, split, reorganized)."""
    id: str
    jurisdiction_node_id: str
    event_type: str                     # "created", "renamed", "merged", "split", "reorganized"
    event_date: str
    previous_state: Optional[dict] = None
    new_state: Optional[dict] = None
    description: Optional[str] = None
    recorded_by_id: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "event_type": self.event_type,
            "event_date": self.event_date,
            "previous_state": self.previous_state,
            "new_state": self.new_state,
            "description": self.description,
            "recorded_by_id": self.recorded_by_id,
            "created_at": self.created_at,
        }


@dataclass
class CaseJurisdictionLink:
    """Additional jurisdiction relationships on a case.
    Primary jurisdiction is on Case.jurisdiction_node_id."""
    id: str
    case_id: str
    jurisdiction_node_id: str
    link_type: str                      # CaseJurisdictionLinkType enum value
    description: Optional[str] = None
    linked_at: str = ""
    linked_by_id: Optional[str] = None
    valid_from: str = ""
    valid_to: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "case_id": self.case_id,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "link_type": self.link_type,
            "description": self.description,
            "linked_at": self.linked_at,
            "linked_by_id": self.linked_by_id,
            "valid_from": self.valid_from,
            "valid_to": self.valid_to,
        }


# ──────────────────────────────────────────────
# Global Entity Identity Index
# ──────────────────────────────────────────────

@dataclass
class GlobalEntity:
    """Global entity identity — links the same real-world entity across Cases.
    This is an identity/linking index, not a graph."""
    canonical_id: str
    entity_type: str
    canonical_name: str
    phones: List[str] = field(default_factory=list)
    accounts: List[str] = field(default_factory=list)
    addresses: List[str] = field(default_factory=list)
    first_seen: str = ""
    last_seen: str = ""
    total_cases: int = 0
    total_jurisdictions: int = 0
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "canonical_id": self.canonical_id,
            "entity_type": self.entity_type,
            "canonical_name": self.canonical_name,
            "phones": self.phones,
            "accounts": self.accounts,
            "addresses": self.addresses,
            "first_seen": self.first_seen,
            "last_seen": self.last_seen,
            "total_cases": self.total_cases,
            "total_jurisdictions": self.total_jurisdictions,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class GlobalEntityLink:
    """Links a global entity to a local entity in a specific Case."""
    id: str
    global_entity_id: str
    case_id: str
    local_entity_id: str                # FK → ResolvedEntity (local to that Case)
    jurisdiction_node_id: str           # FK → JurisdictionNode (from the Case)
    confidence: float = 0.0             # Matching confidence
    match_type: str = ""                # "phone_exact", "name_fuzzy", "account_exact"
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "global_entity_id": self.global_entity_id,
            "case_id": self.case_id,
            "local_entity_id": self.local_entity_id,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "confidence": self.confidence,
            "match_type": self.match_type,
            "created_at": self.created_at,
        }


@dataclass
class CrossCaseAlert:
    """Alert when an entity appears in multiple Cases across jurisdictions."""
    id: str
    global_entity_id: str
    severity: str                       # CrossCaseAlertSeverity enum value
    case_ids: List[str] = field(default_factory=list)
    jurisdiction_node_ids: List[str] = field(default_factory=list)
    recommendation: str = ""
    created_at: str = ""
    status: str = "ACTIVE"              # "ACTIVE", "REVIEWED", "DISMISSED"
    reviewed_by_id: Optional[str] = None
    reviewed_at: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "global_entity_id": self.global_entity_id,
            "severity": self.severity,
            "case_ids": self.case_ids,
            "jurisdiction_node_ids": self.jurisdiction_node_ids,
            "recommendation": self.recommendation,
            "created_at": self.created_at,
            "status": self.status,
            "reviewed_by_id": self.reviewed_by_id,
            "reviewed_at": self.reviewed_at,
        }


# ──────────────────────────────────────────────
# CaseRelationship
# ──────────────────────────────────────────────

@dataclass
class CaseRelationship:
    """Current assessment of how two independent Cases relate.
    Preserves evolution of the relationship over time."""
    id: str
    case_a_id: str                      # FK → Case (smaller id, for ordering)
    case_b_id: str                      # FK → Case (larger id, for ordering)
    initial_observation: str            # CaseRelationshipAssessment (never changes)
    current_assessment: str             # CaseRelationshipAssessment
    confidence: float = 0.0             # 0.0–1.0
    evidence_summary: str = ""
    detected_by: str = "SYSTEM"         # SYSTEM | INVESTIGATOR
    status: str = "SUGGESTED"           # CaseRelationshipStatus
    confirmed_by_id: Optional[str] = None  # FK → User (null for system-detected)
    confirmed_at: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "case_a_id": self.case_a_id,
            "case_b_id": self.case_b_id,
            "initial_observation": self.initial_observation,
            "current_assessment": self.current_assessment,
            "confidence": self.confidence,
            "evidence_summary": self.evidence_summary,
            "detected_by": self.detected_by,
            "status": self.status,
            "confirmed_by_id": self.confirmed_by_id,
            "confirmed_at": self.confirmed_at,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class CaseRelationshipHistory:
    """Audit trail of CaseRelationship evolution over time."""
    id: str
    case_relationship_id: str           # FK → CaseRelationship
    previous_assessment: Optional[str] = None  # null for initial
    new_assessment: str = ""
    previous_status: Optional[str] = None
    new_status: str = ""
    previous_confidence: Optional[float] = None
    new_confidence: float = 0.0
    changed_by_id: Optional[str] = None  # FK → User (null for system)
    change_reason: str = ""
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "case_relationship_id": self.case_relationship_id,
            "previous_assessment": self.previous_assessment,
            "new_assessment": self.new_assessment,
            "previous_status": self.previous_status,
            "new_status": self.new_status,
            "previous_confidence": self.previous_confidence,
            "new_confidence": self.new_confidence,
            "changed_by_id": self.changed_by_id,
            "change_reason": self.change_reason,
            "created_at": self.created_at,
        }


# ──────────────────────────────────────────────
# CaseAccess
# ──────────────────────────────────────────────

@dataclass
class CaseAccess:
    """Authorization: who may access which Cases.
    Separate from InvestigationWorkspace."""
    id: str
    user_id: str                        # FK → User
    case_id: str                        # FK → Case
    access_level: str = "READ"          # CaseAccessLevel
    granted_by_id: str = ""             # FK → User
    granted_at: str = ""
    expires_at: Optional[str] = None

    def to_dict(self):
        return {
            "id": self.id,
            "user_id": self.user_id,
            "case_id": self.case_id,
            "access_level": self.access_level,
            "granted_by_id": self.granted_by_id,
            "granted_at": self.granted_at,
            "expires_at": self.expires_at,
        }


# ──────────────────────────────────────────────
# InvestigationWorkspace
# ──────────────────────────────────────────────

@dataclass
class InvestigationWorkspace:
    """Investigator's working context over authorized Cases.
    Does NOT determine authorization — CaseAccess does that."""
    id: str
    name: str
    description: Optional[str] = None
    created_by_id: str = ""             # FK → User
    jurisdiction_node_id: Optional[str] = None  # FK → JurisdictionNode
    status: str = "ACTIVE"              # WorkspaceStatus
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "created_by_id": self.created_by_id,
            "jurisdiction_node_id": self.jurisdiction_node_id,
            "status": self.status,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class WorkspaceCase:
    """Junction: InvestigationWorkspace ↔ Case.
    Cases are not owned by the workspace. Same Case may be in multiple workspaces."""
    id: str
    workspace_id: str                   # FK → InvestigationWorkspace
    case_id: str                        # FK → Case
    added_by_id: str = ""               # FK → User
    added_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "workspace_id": self.workspace_id,
            "case_id": self.case_id,
            "added_by_id": self.added_by_id,
            "added_at": self.added_at,
        }


@dataclass
class WorkspaceMember:
    """Junction: InvestigationWorkspace ↔ User.
    Workspace membership does NOT grant Case access."""
    id: str
    workspace_id: str                   # FK → InvestigationWorkspace
    user_id: str                        # FK → User
    role: str = "MEMBER"                # WorkspaceRole
    joined_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "workspace_id": self.workspace_id,
            "user_id": self.user_id,
            "role": self.role,
            "joined_at": self.joined_at,
        }


# ──────────────────────────────────────────────
# AnalysisRun
# ──────────────────────────────────────────────

@dataclass
class AnalysisRun:
    """Immutable analytical computation over a fixed Case scope.
    Separate from PipelineRun (which tracks Case processing)."""
    id: str
    workspace_id: Optional[str] = None  # FK → InvestigationWorkspace
    created_by_id: str = ""             # FK → User
    scope_type: str = "LOCAL"           # AnalysisRunScopeType
    description: Optional[str] = None
    pipeline_version: str = ""
    model_versions: dict = field(default_factory=dict)
    status: str = "RUNNING"             # AnalysisRunStatus
    started_at: str = ""
    completed_at: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "workspace_id": self.workspace_id,
            "created_by_id": self.created_by_id,
            "scope_type": self.scope_type,
            "description": self.description,
            "pipeline_version": self.pipeline_version,
            "model_versions": self.model_versions,
            "status": self.status,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
            "created_at": self.created_at,
        }


@dataclass
class AnalysisRunCase:
    """Junction: AnalysisRun ↔ Case.
    Authoritative relational representation of which Cases were analyzed."""
    id: str
    analysis_run_id: str                # FK → AnalysisRun
    case_id: str                        # FK → Case

    def to_dict(self):
        return {
            "id": self.id,
            "analysis_run_id": self.analysis_run_id,
            "case_id": self.case_id,
        }


@dataclass
class AnalysisRunResult:
    """Derived historical artifact of analysis outputs.
    Contains input snapshots written once at completion, never updated.
    Also contains derived outputs — NOT authoritative source for Case/FIR/Entity data."""
    id: str
    analysis_run_id: str                # FK → AnalysisRun (one-to-one)
    # Input snapshots — written once at completion, never updated
    case_relationships_snapshot: Optional[list] = None
    global_entity_links_snapshot: Optional[list] = None
    # Derived outputs — NOT authoritative source
    merged_graph_nodes: Optional[list] = None
    merged_graph_edges: Optional[list] = None
    analytics: Optional[dict] = None
    ml_outputs: Optional[dict] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "analysis_run_id": self.analysis_run_id,
            "case_relationships_snapshot": self.case_relationships_snapshot,
            "global_entity_links_snapshot": self.global_entity_links_snapshot,
            "merged_graph_nodes": self.merged_graph_nodes,
            "merged_graph_edges": self.merged_graph_edges,
            "analytics": self.analytics,
            "ml_outputs": self.ml_outputs,
            "created_at": self.created_at,
        }


# ──────────────────────────────────────────────
# Finding
# ──────────────────────────────────────────────

@dataclass
class Finding:
    """Conclusions/hypotheses/critic output tied to an AnalysisRun.
    Persistent objects with stable references and critic evaluation."""
    id: str
    analysis_run_id: str                # FK → AnalysisRun
    finding_type: str                   # FindingType
    title: str
    description: str = ""
    confidence: float = 0.0             # 0.0–1.0
    # Stable references
    supporting_case_ids: Optional[list] = None
    supporting_entity_ids: Optional[list] = None
    supporting_edge_descriptions: Optional[list] = None
    supporting_evidence_ids: Optional[list] = None
    # Critic evaluation
    critic_status: str = "PENDING"      # CriticStatus
    critic_notes: Optional[str] = None
    critic_confidence: Optional[float] = None
    # Provenance
    created_by_id: Optional[str] = None  # null for system-generated
    created_at: str = ""
    updated_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "analysis_run_id": self.analysis_run_id,
            "finding_type": self.finding_type,
            "title": self.title,
            "description": self.description,
            "confidence": self.confidence,
            "supporting_case_ids": self.supporting_case_ids,
            "supporting_entity_ids": self.supporting_entity_ids,
            "supporting_edge_descriptions": self.supporting_edge_descriptions,
            "supporting_evidence_ids": self.supporting_evidence_ids,
            "critic_status": self.critic_status,
            "critic_notes": self.critic_notes,
            "critic_confidence": self.critic_confidence,
            "created_by_id": self.created_by_id,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


# ──────────────────────────────────────────────
# FIR Lifecycle History
# ──────────────────────────────────────────────

@dataclass
class FIRLifecycleHistory:
    """Audit trail of FIR lifecycle transitions.
    Each transition records dimension, previous/new value, actor, timestamp, reason."""
    id: str
    fir_id: str                         # FK → FIR
    dimension: str                      # FIRLifecycleDimension
    previous_value: Optional[str] = None  # null for initial
    new_value: str = ""
    changed_by_id: str = ""             # FK → User
    changed_at: str = ""
    reason: str = ""
    authority_reference: Optional[str] = None
    created_at: str = ""

    def to_dict(self):
        return {
            "id": self.id,
            "fir_id": self.fir_id,
            "dimension": self.dimension,
            "previous_value": self.previous_value,
            "new_value": self.new_value,
            "changed_by_id": self.changed_by_id,
            "changed_at": self.changed_at,
            "reason": self.reason,
            "authority_reference": self.authority_reference,
            "created_at": self.created_at,
        }